### ISSUE TITLE
https://deeplearning.mit.edu/ not available

### ISSUE THREAD

**Issue by tk-o** [lexfridman/deepcars#34]
https://deeplearning.mit.edu/ can't be accessed — could you please take a look at that? This seems to be a DB connection issue.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/3687215/211190623-52ae6ba6-7b76-41a5-8629-d5e63daf7d8e.png">

Thank you for your work, Lex 🤝

**Comment by jeanmichelroy** [comment]
FYI it was a temporary issue, works now. however as noted on the specific repository selfdrivingcars.mit.edu no longer works
